### ISSUE TITLE
Beta 56 is out

### ISSUE THREAD

**Issue by datinc** [abynim/Sketch-Headers#22]
Beta 56 is out and I am trying to export the headers. I am running `class-dump -r SketchModel.framework` and receiving only errors. What command could I run to export those files?

PS: At the time of writing this the beta branch has not been updated.

**Comment by datinc** [comment]
Was able to output the headers by building the latest class-dump from here https://github.com/nygard/class-dump

**Comment by abynim** [comment]
Updated the betas branch here as well. Thanks for the nudge 👍
