### ISSUE TITLE
textBehaviourLabelString in version 61

### ISSUE THREAD

**Issue by Miniplop** [abynim/Sketch-Headers#23]
Hello @abynim 👋, I build a plugin where I use `textBehaviourLabelString` declared in `MSTextLayer-UISupport.h` for getting textBehaviour name like 'Auto' / 'Fixed' or 'Auto Height'. 

In the version 61 sketch use verticalAlignement / textAlignment for storing this information and now this data is store as int. Is there a new function or a new way to get the string according this number ?

Thank you for your help

**Comment by abynim** [comment]
Sorry, I have no idea about this. I would suggest posting your question on the plugins forum so more people can see it: https://sketchplugins.com

**Comment by Miniplop** [comment]
thank you @abynim 

I found the solution on the forum. The solution is to use textBehaviour MSTextLayer property to get an enum '1'/'2'/'3' corresponding to 'Auto Width'/'Auto Height'/'Fixed Size'

Feel free to close the issue :)
