### ISSUE TITLE
Consider adding more frameworks

### ISSUE THREAD

**Issue by KevinGutowski** [abynim/Sketch-Headers#24]
I need to get headers for the Chocolat framework. Would be nice to have all the frameworks added to this repo!

**Comment by abynim** [comment]
Done: https://github.com/abynim/sketch-headers-exporter/commit/dc2b29c6d35532101d29e0d36549a4111f341342

Those classes should show up the next time headers are exported.

**Comment by KevinGutowski** [comment]
Woo thanks a bunch! :D Was trying to see how hard it would be to try and write a utility library for interacting/creating Sketch UI components to be used in plugins.
