### ISSUE TITLE
Sketch 67 symbolMaster.createSymbolInstance API not work

### ISSUE THREAD

**Issue by yvanwangl** [abynim/Sketch-Headers#25]
when i import a library sketch file, the symbolMaster.createSymbolInstance API not work:
```
const document = context.document;
const symbolReferences = library.getImportableSymbolReferencesForDocument(document);
symbolReferences. forEach(ref => {
   const symbolMaster = ref.import();
   const instance = symbolMaster.createNewInstance();
})
```
this is work before sketch 67

**Comment by abynim** [comment]
`context.document` is a reference to the native `MSDocument` object. You probably want to run this with the JS Document object which is accessed differently. 

Try changing your first line to: 
```
const document = require('sketch/dom').getSelectedDocument()
```

**Comment by yvanwangl** [comment]
@abynim sorry , document value is correct `const document = require('sketch/dom').getSelectedDocument()`,
when update sketch to 67, `symbolMaster.createNewInstance()` is not work.
sketch 66.1
![image](https://user-images.githubusercontent.com/11405052/86557222-1e1e9680-bf88-11ea-9529-f8bf7ffb14fa.png)

sketch 67
![image](https://user-images.githubusercontent.com/11405052/86557186-06471280-bf88-11ea-9b23-ebbc0a1bebb7.png)

**Comment by abynim** [comment]
Weird! I just tried this in Sketch 67 and it seems to work. Have you tried just logging all the values to the console? I would try logging the values of `library`, `ref`, `symbolMaster` and see if they're all accurate. It's probably breaking somewhere else.

If you're still having trouble I would suggest posting on the plugins forum, in case someone else has run into the same issue: https://sketchplugins.com
