### ISSUE TITLE
Too many files in directory

### ISSUE THREAD

**Issue by akolpakov** [abynim/Sketch-Headers#6]
When you open `Headers` directory on GitHub, it doesn't show all files, warning message appears:

```
Sorry, we had to truncate this directory to 1,000 files. 482 entries were omitted from the list.
```

Of course, you can clone this repo. But very handy to use it through the web.
My suggestion is to divide it to sub directories. I see that every file has own prefix `AF`, `BC`, `MF` and so on, maybe classify them by prefix.

**Comment by abynim** [comment]
@akolpakov when you open the Headers directory on Github, type `t` to search for and jump to the file you are looking for.
