### ISSUE TITLE
Export requests are failing in update 44?

### ISSUE THREAD

**Issue by geraldeersteling** [abynim/Sketch-Headers#9]
Hi,

Does anyone knows what they changed in exporting artboards in update 44?
I wrote a plugin to export artboards, but with the update the exported artboards are "empty".
I _do_ see the PNG exported to the correct path (and everything is correct; the size, name, format etc.) but the PNG is "empty" (see screenshot)

![screen shot 2017-05-17 at 15 50 41](https://cloud.githubusercontent.com/assets/5538718/26157109/9bfb12d8-3b18-11e7-9102-1b27f07e80be.png)

---

The snippet I'm using to export the file is:

```javascript
doc = context.document
var path // <-- assume this is a valid file URL
var layer // <-- assume this is a valid MSArtboardGroup
if (!layer.isLayerExportable()) {
    print([NSString stringWithFormat:"The layer [%@] is not exportable!", layer.name()])
    return
}

var requests = NSMutableArray.array()

for (var i = 0; i < layer.exportOptions().exportFormats().length; i++) {
    var format = layer.exportOptions().exportFormats()[i]
    var request = [MSExportRequest exportRequestFromExportFormat:format layer:layer inRect:layer.absoluteInfluenceRect() useIDForName:true]
    request.name = (format.name()) ? format.name() : request.name()
    requests.addObject(request)
}

// Loop all requests and export each of them
for(var k = 0; k < requests.length; k++) {
    var request = requests[k]
    exportName = request.name()
    exportPath = [path stringByAppendingPathComponent:exportName]
    exportPath = [exportPath stringByAppendingPathExtension:request.format()]

    [doc saveArtboardOrSlice:request toFile:exportPath]
    var msg = [NSString stringWithFormat:"Saved: %@ to %@", exportName, exportPath]
    log(msg)
}
```

Before the snippet worked perfectly, but right now I _do_ see the message that the file is saved/exported but encounter the problems I stated before.

Does anyone knows what must be changed to export correctly?

**Comment by abynim** [comment]
Please post plugin-related questions on the forum at http://sketchplugins.com
